- name: Manage NGINX state
  hosts: linux
  become: yes
  vars:
    nginx_enabled: true  # change to false to disable nginx

  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present
